name: build and deploy to gh-pages

on:
  push:
    branches: [master]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: setup python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dev-dependencies
      run: pip install -r requirements.txt -r requirements-dev.txt
    - name: coverage test
      run: nosetests -c .noserc
    - name: build wheel
      run: python setup.py bdist_wheel
    - name: create index
      run: dir2pi -S dist
    - name: merge contents
      run: cp -r dist/simple/ cover/dist/
    - name: disable jekyll
      run: touch cover/.nojekyll
    - name: deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./cover
