name: CI

on:
  push:
    branches-ignore: [master, gh-pages]

jobs:
  nosetest:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        pyver: ["3.6", "3.7", "3.8"]

    steps:
    - uses: actions/checkout@v1
    - name: setup python ${{ matrix.pyver }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.pyver }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
    - name: run test
      run: |
        nosetests -c .noserc
